### ISSUE TITLE
Unreliable E2E Test in home.e2e.js

### ISSUE THREAD

**Issue by Ken-Lo** [gocardless/splash-pages#259]
A significant number of builds (probably ~25%) are failing due to the "Swapping languages - lets you navigate to a page and then swap languages" E2E test:
```
[chrome ANY #1-1] Specs: /home/ubuntu/splash-pages/app/pages/home/home.e2e.js
[chrome ANY #1-1] 
[chrome ANY #1-1] Using ChromeDriver directly...
[chrome ANY #1-1] Navigating to the Pro product
[chrome ANY #1-1]   lets the user navigate to /pro - pass
[chrome ANY #1-1] Swapping languages
[chrome ANY #1-1]   lets you navigate to a page and then swap languages - fail
[chrome ANY #1-1] 
[chrome ANY #1-1] 
[chrome ANY #1-1]   1) Swapping languages lets you navigate to a page and then swap languages
[chrome ANY #1-1]   at 4.744s [Tue, 28 Jul 2015 14:24:28 GMT]
[chrome ANY #1-1]    Message:
[chrome ANY #1-1]      Expected false to be true.
[chrome ANY #1-1]    Stacktrace:
[chrome ANY #1-1]      Error: Failed expectation
[chrome ANY #1-1]     at [object Object].<anonymous> (/home/ubuntu/splash-pages/app/pages/home/home.e2e.js:21:87)
[chrome ANY #1-1]     at runMicrotasksCallback (node.js:337:7)
[chrome ANY #1-1]     at process._tickCallback (node.js:355:11)
[chrome ANY #1-1] 
[chrome ANY #1-1] Finished in 4.747 seconds
[chrome ANY #1-1] 2 tests, 2 assertions, 1 failure
[chrome ANY #1-1] 
```
It normally gets resolved by manually retrying the build. Should probably find a longer-term solution and make this work more reliably?

**Comment by jackfranklin** [comment]
@Ken-Lo I'll take a look tomorrow. We should squish flakes like this.
